apiVersion: v1
kind: Service
metadata:
  name: sqlserver2019-service
spec:
  ports:
  - name: sqlserver2019-ports
    port: 1433
    targetPort: 1433
  selector:
    name: sqlserver2019-pod
  type: LoadBalancer